pmndrs/react-ogl

src/utils.ts, tests/__snapshots__/utils.test.tsx.snap, tests/utils.test.tsx
Fix for #8
Fix apply a uniforms without assigning uniform property, only update known values in one.
Generic problem: uniform can already have applied value from base class or has external setter that can change value.
We shouldn't reset already defined uniforms, we should merge from props and override.
Should be tested!
=> fix uniform update

src/shared/utils.ts
State MUST store actual reference to subscribed, but `unsubscribe` produce new Array which will unmatch with same field in state.
I use custom render loop and for me this is critical bug.
I can't use boxed loop because it use `requestAnimationFrame` from window, that not working in XR mode (XRSession has own requestAnimationFrame that needs to use instead of window.requestAnimationFrame)
```
const animate = (time?: number) => {
state.animation = renderer.requestAnimationFrame(animate);
// update OGL useFrame
subscribed.forEach((ref: any) => ref.current?.(state, time));
// Render to screen
renderer.render({ scene, camera, frustumCull: false } as any);
};
state.animation = renderer.requestAnimationFrame(animate);
```
=> fix: not change subscribed reference

src/reconciler.ts, src/utils.ts, tests/index.test.tsx
Fixes a potential issue with attach and suspense by relegating the actual attachment until mount, where scene children are finalized.
Also cleans up internal react fiber handoff when swapping, creating, and inspecting instances in dev tools. Hopefully, this is the culprit of #4.
=> refactor(core): attach on mount, correctly handle fiber handoff

.eslintrc, src/constants.ts, src/reconciler.ts
Implements #15 by accepting a `passGL` argument in `extend` which passes the active gl context automatically to the element in construction. Importantly, this will affect all elements passed in the call to `extend` or any elements who extend them. Passing gl as an arg to these elements will still work as before, however, it is unneeded.
```js
// Marks both classes as effectful and will receive an effect
extend({ CustomClass1, CustomClass2 }, true)
```
```diff
- const gl = useOGL()
- <customClass1 args={[gl]} prop={value} />
- <customClass2 args={[gl]} prop={value} />
+ <customClass1 prop={value} />
+ <customClass2 prop={value} />
```
This is enabled for core classes to let users use props instead of args for common classes like meshes, materials, geometry, and so on.
```js
<program …
```
=> feat(core): customize gl behavior via extend

src/types.ts, src/utils.ts, tests/index.test.tsx
Expands the `attach` prop by accepting an attach function in addition to a string. This is 1-1 with [R3F v8's unified attach API](https://docs.pmnd.rs/react-three-fiber/tutorials/v8-migration-guide#unified-attach-api).
```js
// will attach to parent.target
<parent>
<child attach="target" />
</parent>
// will attach to parent.target.subtarget
<parent>
<child attach="target-subtarget" />
</parent>
// will attach to parent.target[0] and parent.target[1], creates an array if parent.target is undefined
// useful for attaching multiple elements to an array
<parent>
<child attach="target-0" />
<child attach="target-1" />
</parent>
// will call child.setParent on mount and child.removeChild unmount
<parent>
<child
attach={(parent, self) => {
self.setParent(parent)
// remove on unmount
return () …
```
=> feat(core): expanded attach

src/Canvas.native.tsx, src/Canvas.tsx, src/events.ts, src/reconciler.ts, src/utils.ts
Trims excess methods and prefers for (key in/of over array or object methods for their interation speed.
=> refactor: cleanup, prefer iterating over cloning into memory

package.json, src/Canvas.native.tsx, yarn.lock
Updates `rollup-include-all` to exclude file exts in name for native resolution, preps the gl context to match OGL's internals, and preserves parameters passed to renderer.render in native contexts.
=> fix(native): prepare ogl context, don't overwrite renderer.render

src/Canvas.native.tsx, src/Canvas.tsx, src/renderer.tsx, src/types.ts
Adds a `size` renderprop to mirror R3F's API for sizing. This can be subscribed to via useOGL.
=> feat: add size render prop

package.json, src/renderer.tsx, src/types.ts, src/utils.ts, yarn.lock
Adds support for WebXR rendering via an XRManager:
```ts
XRManager {
session: XRSession | null
setSession(session: XRSession | null): void
connect(session: XRSession): void
disconnect(): void
}
//
const renderer = useOGL(state => state.renderer)
const xr = useOGL(state => state.xr)
useEffect(() => {
let mounted = true
(async () => {
const session = await navigator.xr.requestSession('immersive-vr', {
optionalFeatures: ['local-floor', 'bounded-floor', 'hand-tracking'],
})
session.updateRenderState({ baseLayer: new XRWebGLLayer(session, renderer.gl) })
if (!mounted) return session.end()
else xr.connect(session)
})()
return () => {
mounted = false
xr.disconnect()
}
}, [renderer, xr])
```
This will augment useFrame subscriptions to access an `XRFrame` while in a session:
```ts
useFrame((state: …
```
=> feat(core): add xr manager, render mode switching

src/reconciler.ts, src/renderer.tsx, src/types.ts, src/utils.ts, tests/index.test.tsx
Fixes an issue where foreign portal targets not instantiated by react-ogl will desync their children during construction and mount.
```jsx
const object = new Transform()
const Box = (props) => (
<mesh {...props}>
<box />
<normalProgram />
</mesh>
)
export default (
<Canvas>
{createPortal(
<>
<Box position={[-1.2, 0, 0]} />
<Box position={[1.2, 0, 0]} />
</>,
object,
)}
<primitive object={object} />
</Canvas>
)
```
=> fix(core): prepare portal targets

src/utils.ts, tests/utils.test.tsx
Fixes #42 where array-like interfaces like ArrayBuffers or those with set properties (i.e. Map) are incorrectly assumed as math classes.
=> fix(core): don't use arraybuffer methods

src/reconciler.ts, src/renderer.tsx, src/types.ts, src/utils.ts, tests/events.test.tsx, tests/hooks.test.tsx, tests/index.test.tsx, tests/native.test.tsx, tests/utils.test.tsx, tests/web.test.tsx
Solves a longstanding issue of OGL's constructor side-effects by creating instances' objects on commit mount instead of alongside instance creation. Instead, instances are descriptors that will create an OGL element once finalized and managed in the tree. This prevents GPU memory leaks that would arise when using suspense or concurrent features whenever instances are discarded and later recreated. Effectful constructors are not a good design, but this way, we work around them.
=> refactor(core): create instances' objects on commit

src/utils.ts, tests/utils.test.tsx
Refactors `resolveAttach` into `resolve` for re-use in `applyProps` or anywhere dash-cased keys need to be resolved.
=> refactor(core): use resolve in applyprops

src/reconciler.ts, tests/index.test.tsx
Fixes attach race conditions with useLayoutEffect by handling container attach for child elements on commit mount. For the root-level container/instance (scene or portal target), this is a no-op.
=> fix(core): handle container append on mount

src/reconciler.ts
Decouples cleanup of old instances in reconstruct from the new instance. Will only manually append/attach the new instance if adding to an already mounted instance (since we use a bottom-up approach with #44).
=> fix(core): decouple previous attach on reconstruct

src/constants.ts, src/reconciler.ts, src/utils.ts, tests/utils.test.tsx
Hardens reconciler and applyProps checks against react-internal props and prevents react-ogl instance props from being applied to objects in applyProps.
=> fix(core): don't diff reserved props, skip instance props in applyProps

src/reconciler.ts, src/utils.ts, tests/index.test.tsx
Updates `attach` reactively on commit update between one or multiple instances (in the case of swapping via state).
=> fix(core): update attach reactively on commit update

examples/src/components/Controls.tsx, package.json, src/reconciler.ts, src/types.ts, src/utils.ts, tests/index.test.tsx, tests/utils.test.tsx, yarn.lock
Continues #28. Uses types from https://github.com/CodyJasonBennett/ogl-types as `@types/ogl` for OGL types.
=> feat: use @types/ogl drop-in

src/reconciler.ts
Fixes an issue where non-attribute props were passed as attributes to OGL.Geometry's constructor, and caused unnecessary reconstruction on update.
=> fix(core): don't set non-attributes as attributes

src/renderer.tsx
`splice` should have a more that 0 in second argument, or it will not remove anything.
=> Fix: stupid mistake in unsubscribe

.eslintrc, examples/src/components/Controls.tsx, examples/src/cubes.tsx, examples/src/draw-modes.tsx, examples/src/primitives.tsx, src/Canvas.native.tsx, src/Canvas.tsx, src/events.native.ts, src/events.ts, src/hooks.ts, src/reconciler.ts, src/renderer.tsx, src/types.ts, src/utils.ts, tests/index.test.tsx, tests/utils.test.tsx, tsconfig.json
Correctly infers return types for `useGraph` and `useLoader` and marks 0.97's helpers as effectful via `extend` for mutable construction.
=> fix(types): mark OGL helpers as effectful, correctly infer hook types

README.md
Adds dedicated documentation for react-ogl and its API, separately from [react-three-fiber](https://github.com/pmndrs/react-three-fiber).
=> chore: add docs, rework information architecture

src/hooks.ts
Mirrors https://github.com/reduxjs/react-redux/pull/1444 with a check for react-native in `useIsomorphicLayoutEffect`, so `useEffect` is only used server-side.
=> fix: use useLayoutEffect in native

src/hooks.ts
Prefers to use internal `useIsomorphicEffect` in `useFrame` to play nice with SSR.
=> fix(useFrame): use isomorphic effects for SSR

.eslintrc, examples/tsconfig.json, package.json, tests/index.test.tsx, tests/utils/setupTests.ts, tsconfig.json, vite.config.js
Webpack does not effectively tree-shake bundled modules, so splitting up the module structure for the web target (see https://github.com/vitejs/vite/issues/5174#issuecomment-1193414981).
Also enables sourcemaps for quality control (since bundles are now divergent), skipping `tsc`.
=> fix: enable tree-shaking in webpack, sourcemaps

vite.config.js
Minimizes distribution size by de-duping sourcemaps and sharing code between web and native entrypoints.
=> fix: optimize distribution size

package.json, src/Canvas.native.tsx, tests/utils/setupTests.ts, yarn.lock
Removes `@expo/browser-polyfill` to play nice with NPM package resolution.
=> fix!: remove native polyfill

src/events.native.ts, src/reconciler.ts, src/renderer.tsx
Fixes withstanding issues from #63 by explicitly importing entry points not defined in `package.json` to play nice with ESM policy.
=> fix: explicitly import entrypoints

README.md, src/reconciler.ts, src/renderer.tsx, src/types.ts, src/utils.ts, tests/index.test.tsx
Mirrors type enhancements from https://github.com/pmndrs/react-three-fiber/pull/2465.
Additionally, OGL types for `JSX.IntrinsicElements` are no longer hard-coded and dynamically mapped to `OGLElements`. This lets us properly follow semver once `@types/ogl` is upstreamed.
The `Node` interface has been simplified and renamed to `OGLElement` to prevent clashing with DOM types:
```tsx
declare module 'react-ogl' {
interface ThreeElements {
customElement: OGLElement<typeof CustomElement>
}
}
extend({ CustomElement })
```
=> refactor(types): dynamically map OGLElements

src/hooks.ts
Fixes #69 by passing src to OGL's TextureLoader.
=> fix(useLoader): pass src to textureloader

README.md, package.json, src/constants.ts, src/hooks.ts, src/reconciler.ts, src/renderer.tsx, src/types.ts, src/utils.ts, tests/index.test.tsx, tests/utils/setupTests.ts
Mirrors container effects from https://github.com/pmndrs/react-three-fiber/pull/2483, moving #44 to before mount and making use of container methods. Also cleans up leaf children to prevent memory leaks from subtrees.
Additionally, Portals now create state enclaves to isolate scenes, cameras, etc. from the root store. This is particularly useful for postprocessing and complex effects.
```tsx
function Component {
// scene & camera are inherited from portal parameters
const { scene, camera, ... } = useOGL()
}
const scene = new OGL.Transform()
const camera = new OGL.Camera()
<transform>
{createPortal(<Component />, scene, { camera })
</transform>
```
=> feat: container effects, recursive dispose, portal state

package.json
Adds the legacy `module` field so Bundlephobia can resolve this package right.
=> experiment: add module field for bundlephobia

package.json, src/Canvas.native.tsx, src/Canvas.tsx, tests/native.test.tsx, tests/utils/setupTests.ts, tests/web.test.tsx, yarn.lock
Implements a context bridge within `Canvas`. This enables react-ogl children to consume context between renderers (e.g. `react-dom` or `react-native`), removing the need for manually bridging context.
```jsx
import * as React from 'react'
import * as ReactDOM from 'react-dom/client'
import { Canvas } from 'react-ogl'
const DOMContext = React.createContext()
function Component() {
// "Hello from react-dom"
console.log(React.useContext(DOMContext))
}
ReactDOM.createRoot(document.getElementById('root')).render(
<DOMContext.Provider value="Hello from react-dom">
<Canvas>
<Component />
</Canvas>
</DOMContext.Provider>,
)
```
=> feat(Canvas): bridge cross-container context

package.json, src/hooks.ts, src/renderer.tsx, tests/hooks.test.tsx, yarn.lock
Adds support for https://github.com/oframe/ogl/pull/188, drops https://github.com/CodyJasonBennett/ogl-types via `@types/ogl`.
=> refactor(types)!: support for OGL v1

package.json, src/renderer.tsx, tests/hooks.test.tsx, yarn.lock
When using a custom renderer, the following warning appears:
This PR fixes the issue by updating Zustand to the latest version.
=> feat: update Zustand to use latest API

src/reconciler.ts
I faced this error using nextjs on react 18. Adding the optional chaining operator seems to fix it.
```
"next": "14.2.3",
"react": "18.3.1",
```
=> Fix ```unstable_act``` error

README.md, examples/src/cubes.tsx, package.json, src/Canvas.native.tsx, src/Canvas.tsx, src/hooks.ts, src/reconciler.ts, src/renderer.tsx, src/types.ts, src/utils.ts, tests/events.test.tsx, tests/hooks.test.tsx, tests/index.test.tsx, tests/native.test.tsx, tests/utils/setupTests.ts, tests/web.test.tsx, vite.config.js, yarn.lock
Mirrors https://github.com/pmndrs/react-three-fiber/issues/3222, https://github.com/pmndrs/react-three-fiber/pull/3224.
=> feat!: React 19
